#  https://peakswc.visualstudio.com/
#  https://medium.com/@dan.cokely/creating-nuget-packages-in-azure-devops-with-azure-pipelines-and-yaml-d6fa30f0f15e

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'MinSizeRel'

steps:

- task: projectversionasvariable@1
  inputs:
    path: 'Directory.Build.props'
    versionTag: 'VersionPrefix'

# - task: NuGetToolInstaller@1



#Build RemoteableWebWindowService Nuget Package
- task: DotNetCoreCLI@2
  displayName: 'Build RemoteableWebWindowService'
  inputs:
    command: build
    projects: 'src\RemoteableWebWindowService\RemoteableWebViewService.csproj'
    arguments: '--configuration $(buildConfiguration)'

#Package RemoteableWebWindowService Nuget Package
- task: DotNetCoreCLI@2
  displayName: 'Package RemoteableWebWindowService'
  inputs:
    command: pack
    packagesToPack: 'src\RemoteableWebWindowService\RemoteableWebViewService.csproj '
    versioningScheme: byPrereleaseNumber
    majorVersion: $(Version.Major)
    minorVersion: $(Version.Minor)
    patchVersion: $(Version.Patch)

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'src\RemoteWebWindow.Blazor.JS'

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'


- task: NuGetCommand@2
  displayName: 'NuGet push packages'
  inputs:
    command: push
    publishVstsFeed: 'RemoteBlazorWebView/Nugets'
    allowPackageConflicts: false
    packagesToPush: 'artifacts/*.nupkg'
 
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'artifacts'
    ArtifactName: 'dropNugets'
    publishLocation: 'Container'
    
    
