name: .NET Core and WPF on Windows

trigger:
  - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: Setup nodejs
      uses: actions/setup-node@v1
    - name: Setup nuget
      uses: nuget/setup-nuget@v1
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
    - name: Yarn
      working-directory: ./src/RemoteWebWindow.Blazor.JS/upstream/aspnetcore/web.js
      run: yarn
    - name: Build BlazorWebView.JS
      working-directory: ./src/RemoteWebWindow.Blazor.JS/
      run: dotnet build --configuration Release
    - name: Build PeakSWC.StaticFiles
      working-directory: ./src/StaticFiles/
      run: dotnet build --configuration Release
    - name: Build RemoteableWebView
      working-directory: ./src/RemoteableWebView/
      run: dotnet build --configuration Release
    - name: Build RemoteBlazorWebView.Wpf
      working-directory: ./src/RemoteBlazorWebView.Wpf/
      run: |
         dotnet restore
         MsBuild.exe RemoteBlazorWebView.Wpf.csproj /t:Build /p:Configuration=Release
    - name: Build RemoteableWebWindowService
         working-directory: ./src/RemoteableWebWindowService/
         run: dotnet build --configuration Release

    - name: Push RemoteBlazorWebView nuget packages
      working-directory: ./
      run: |
        dotnet nuget push .\src\BlazorWebView\packages\BlazorWebView*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        dotnet nuget push .\src\BlazorWebView.Wpf\packages\BlazorWebView.Wpf*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json