<Project Sdk="Microsoft.NET.Sdk.Worker">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<Platforms>x64</Platforms>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<NoWarn>$(NoWarn);CA1416</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Grpc.Net.ClientFactory" Version="2.71.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="9.0.4" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.4" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.4" />
		
		<PackageReference Include="Grpc.Net.Client" Version="2.71.0" />
		<PackageReference Include="Google.Protobuf" Version="3.30.2" />
		<PackageReference Include="Grpc.Tools" Version="2.72.0">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="System.Management" Version="9.0.4" />
		
	</ItemGroup>

	<ItemGroup>
		<Protobuf Include="Protos\filewatcher.proto" GrpcServices="Client" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Properties\PublishProfiles\" />
	</ItemGroup>
</Project>
