<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net9-windows</TargetFramework>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<Configurations>Debug;Release</Configurations>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<DefineConstants>xDEBUG_SERVER;xPROFILED_SERVER</DefineConstants>
		<Platforms>x64</Platforms>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="BaseTestFixture.cs" />
	  <Compile Remove="Local\TestBlazorFormFixtureOld.cs" />
	  <Compile Remove="Local\TestLocalBlazorFormOld.cs" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="Local\BaseTestFixture.cs" />
	</ItemGroup>

	<ItemGroup>
		<Protobuf Include="..\..\..\Protos\webview.proto" GrpcServices="Client" Link="Protos\webview.proto" />
		<PackageReference Include="coverlet.collector" Version="6.0.4">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="FluentAssertions" Version="8.2.0" />
		<PackageReference Include="Google.Protobuf" Version="3.30.2" />
		<PackageReference Include="Grpc.Net.Client" Version="2.71.0" />
		<PackageReference Include="Grpc.Net.ClientFactory" Version="2.71.0" />
		<PackageReference Include="Grpc.Net.Client.Web" Version="2.71.0" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="9.0.4" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.4" />
		<PackageReference Include="System.Management" Version="9.0.4" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
		<PackageReference Include="Microsoft.Playwright" Version="1.52.0" />
		<PackageReference Include="PeakSWC.RemoteBlazorWebView.Wpf" Version="9.0.4" />
		<PackageReference Include="xunit" Version="2.9.3" />
		<PackageReference Include="System.IO.FileSystem.AccessControl" Version="5.0.0" />
		<PackageReference Include="Serilog.Extensions.Logging.File" Version="3.0.0" />
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.0">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>

		<Using Include="Xunit" />
		<None Include="..\..\src\Benchmarks\FilePOC\Client\publish\Client.exe">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<Folder Include="Protos\" />
		<ProjectReference Include="..\..\src\RemoteWebView\RemoteWebView.csproj" />
		<ProjectReference Include="..\..\src\RemoteBlazorWebView.WinForms\RemoteBlazorWebView.WindowsForms.csproj" />
		<ProjectReference Include="..\..\src\RemoteBlazorWebView\RemoteBlazorWebView.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Content Update="wwwroot\css\app.css">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Update="wwwroot\css\site.css">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Update="wwwroot\favicon.ico">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Update="wwwroot\index.html">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

</Project>
