<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <LangVersion>latest</LangVersion>
	  <EnablePreviewFeatures>true</EnablePreviewFeatures>
	  <Platforms>x64</Platforms>
	  <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Utilitiesx.cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\..\test\FileSyncServer.Tests\Utilities.cs" Link="Utilities.cs" />
  </ItemGroup>
	<ItemGroup>
		<PackageReference Include="BenchmarkDotNet" Version="0.14.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0-preview.1.25080.5" />
		<PackageReference Include="Google.Protobuf" Version="3.29.3" />
		<PackageReference Include="Grpc.Net.Client" Version="2.67.0" />
		<PackageReference Include="Grpc.Net.Client.Web" Version="2.67.0" />
		<PackageReference Include="PeakSWC.RemoteWebView" Version="9.0.2" />
		<PackageReference Include="System.Management" Version="10.0.0-preview.1.25080.5" />
		<!--<ProjectReference Include="..\..\RemoteWebView\RemoteWebView.csproj" />-->
		<Protobuf Include="..\..\src\Protos\webview.proto" GrpcServices="Client" Link="Protos\webview.proto" />
	</ItemGroup>
	<PropertyGroup>
		<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
		<GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
	</PropertyGroup>

</Project>
