<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<InvariantGlobalization>true</InvariantGlobalization>
		<Platforms>x64</Platforms>
		<NoWarn>$(NoWarn);CA1416</NoWarn>

	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Google.Protobuf" Version="3.31.1" />
		<PackageReference Include="Grpc.Net.Client" Version="2.71.0" />
		<PackageReference Include="Grpc.Net.Client.Web" Version="2.71.0" />
		<PackageReference Include="System.Diagnostics.EventLog" Version="10.0.0-preview.4.25258.110" />
		<ProjectReference Include="..\..\RemoteWebView\RemoteWebView.csproj" />
		<Protobuf Include="..\..\src\Protos\webview.proto" GrpcServices="Client" Link="Protos\webview.proto" />
	</ItemGroup>

</Project>
